# Changes here will be overwritten by Copier
_commit: v1.0.11
_src_path: gh:myrontuttle/python-copier-template
author_email: myrongt@gmail.com
author_name: Myron Tuttle
author_username: myrontuttle
minimal_python_version: '3.9'
package_name: musicdl
project_description: Music Downloader
project_name: musicdl
software_license: MIT License
